packages:
  - cli
  - apps/*
  - packages/*

supportedArchitectures:
  os:
    - current
    - linux
  cpu:
    - current
    - x64

onlyBuiltDependencies:
  - "@bufbuild/buf"
  - electron
  - esbuild
  - microsandbox
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.2.9
  vitest: 4.1.10
  vite-plus: 0.2.9
overrides:
  "@trytilde/sdk-vercel-ai-node>@ai-sdk/mcp": "2.0.32"
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
