packages:
  - cli
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - "@trytilde/api-client"
  - "@bufbuild/buf"
  - electron
  - esbuild
  - microsandbox
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.2.9
  vitest: 4.1.10
  vite-plus: 0.2.9
overrides:
  vite: "catalog:"
  vitest: "catalog:"
packageExtensions:
  "@trytilde/api-client@*":
    dependencies:
      "@types/node": "24.3.0"
      typescript: "5.9.3"
      vite: "8.0.16"
      vite-plugin-dts: "4.5.4"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
