import { lstat, mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import { dirname, relative, resolve, sep } from "node:path";
import repositoryConfig from "../openbot.config.js";

const root = resolve(process.cwd());
const output = resolve(root, "apps/server/src/generated/repository.ts");
const maxFiles = 1_000;
const maxFileBytes = 2 * 1024 * 1024;
const maxTotalBytes = 20 * 1024 * 1024;

export async function discoverRepositoryFiles(base = root): Promise<string[]> {
  const candidates = [
    "openbot.config.ts",
    repositoryConfig.agents.directory,
    repositoryConfig.providers.directory,
    repositoryConfig.skills.directory,
    repositoryConfig.sandbox.assetsDirectory,
    repositoryConfig.sandbox.bootstrap,
    repositoryConfig.sandbox.secretsManifest,
  ];
  const files: string[] = [];
  for (const candidate of candidates) await walk(resolve(base, candidate), base, files);
  if (files.length > maxFiles) throw new Error(`Repository configuration exceeds ${maxFiles} files`);
  return files.sort();
}

async function walk(path: string, base: string, files: string[]): Promise<void> {
  let stat;
  try { stat = await lstat(path); } catch { return; }
  if (stat.isSymbolicLink()) throw new Error(`Repository configuration may not contain symlinks: ${relative(base, path)}`);
  if (stat.isDirectory()) {
    for (const entry of await readdir(path)) await walk(resolve(path, entry), base, files);
    return;
  }
  if (!stat.isFile()) throw new Error(`Unsupported repository entry: ${relative(base, path)}`);
  if (stat.size > maxFileBytes) throw new Error(`Repository file exceeds ${maxFileBytes} bytes: ${relative(base, path)}`);
  files.push(relative(base, path).split(sep).join("/"));
}

export function generatedSource(files: readonly string[], agentsDirectory = repositoryConfig.agents.directory, providersDirectory = repositoryConfig.providers.directory): string {
  const agentPattern = new RegExp(`^${escapeRegex(agentsDirectory.replace(/\/$/, ""))}/[^/]+\\.[cm]?[jt]s$`);
  const agentFiles = files.filter((path) => agentPattern.test(path) && !path.includes(".test."));
  const providerPattern = new RegExp(`^${escapeRegex(providersDirectory.replace(/\/$/, ""))}/[^/]+/index\\.[cm]?[jt]s$`);
  const providerFiles = files.filter((path) => providerPattern.test(path));
  const imports = [
    'import config from "../../../../openbot.config.js";',
    ...agentFiles.map((path, index) => `import * as agent${index} from ${JSON.stringify(`../../../../${path.replace(/\.[^.]+$/, ".js")}`)};`),
    ...providerFiles.map((path, index) => `import provider${index} from ${JSON.stringify(`../../../../${path.replace(/\.[^.]+$/, ".js")}`)};`),
  ];
  return [
    "// Generated by pnpm openbot:generate. Do not edit.",
    ...imports,
    "export const repositoryConfig = config;",
    `export const repositoryAgents = [${agentFiles.map((_, index) => `agent${index}`).join(", ")}] as const;`,
    `export const repositoryAgentPaths = ${JSON.stringify(agentFiles)} as const;`,
    `export const repositoryProviderPlugins = [${providerFiles.map((_, index) => `provider${index}`).join(", ")}] as const;`,
    `export const repositoryProviderPaths = ${JSON.stringify(providerFiles)} as const;`,
    `export const repositoryFilePaths = ${JSON.stringify(files)} as const;`,
    "",
  ].join("\n");
}

function escapeRegex(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

async function main(): Promise<void> {
  const files = await discoverRepositoryFiles();
  let total = 0;
  for (const path of files) total += (await readFile(resolve(root, path))).byteLength;
  if (total > maxTotalBytes) throw new Error(`Repository configuration exceeds ${maxTotalBytes} bytes`);
  await mkdir(dirname(output), { recursive: true });
  await writeFile(output, generatedSource(files));
  process.stdout.write(`Generated repository manifest for ${files.length} files.\n`);
}

if (process.argv[1] && resolve(process.argv[1]) === resolve(new URL(import.meta.url).pathname)) await main();
